dist: trusty
language: php

cache:
  bundler: true
  directories:
    - "$HOME/.composer/cache"
    - "$HOME/.drush/cache"

php:
  - 7.1

env:
  - VERSION=HEAD
  # The final CI slot should be used to test the update path from the oldest
  # available database fixture.
  - VERSION=3.0.0

matrix:
  fast_finish: true

addons:
  chrome: stable

before_install:
  - phpenv config-add ./tests/travis.php.ini
  - phpenv rehash

  - composer self-update
  - composer --version
  - google-chrome-stable --version

  - export ORCA=$TRAVIS_BUILD_DIR/../orca
  - export ORCA_FIXTURE=$ORCA-build
  - export ORCA_SUT=$TRAVIS_REPO_SLUG
  - export ORCA_PACKAGES_CONFIG_ALTER=../lightning/tests/orca.yml

  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - export PATH="$ORCA/bin:$PATH"
  - export PATH="$ORCA/vendor/bin:$PATH"
  - export PATH="$ORCA_FIXTURE/vendor/bin:$PATH"

  # Add the ORCA repository.
  - composer config --global repositories.orca vcs "https://github.com/acquia/orca"
  # Use a personal access token to authenticate with GitHub, to avoid being
  # rate-limited. The token is configured in the Travis CI repository settings.
  - composer config --global github-oauth.github.com $GITHUB_OAUTH_TOKEN

install:
  # Install ORCA so that we can build the fixture using that.
  - composer create-project --stability dev --no-dev acquia/orca:^1.0.0-alpha6 $ORCA
  - "$ORCA/bin/travis/install 8.x-3.x"

  # Run ORCA static analysis tools.
  - orca static-analysis:run ./

  # Use ORCA to build the code base.
  - orca fixture:init -f --sut $ORCA_SUT --dev --profile lightning
  # Install dev dependencies.
  - composer require --dev drupal/console --working-dir $ORCA_FIXTURE --no-update
  # Update in a separate step to prevent lock file version conflicts.
  - composer update --working-dir $ORCA_FIXTURE

before_script:
  - cd $ORCA_FIXTURE/docroot
  - $TRAVIS_BUILD_DIR/update.sh $VERSION

script:
  - orca tests:run --sut $ORCA_SUT

after_failure:
  - drush watchdog:show --count=100 --severity=Error --extended
